### ISSUE TITLE
Should We Make Vanilla Class Implement By ASM?

### ISSUE THREAD

**Issue by CrafterKina** [MinecraftModderJapan/MinecraftModCooperationAPI#1]
### Summary

バニラクラスもASM使うなりしてインターフェースを実装させるべきなのでは？
### Content

バニラクラスに対してASMを使って当APIのインターフェースを実装させる。
### Reason

当APIで追加するインターフェースへのメソッドの追加がめんどくさくなりそう。
例えば、ポーション系の処理でPotionを継承しない独自のエフェクトを追加するやつなんかに対応しようとすると2つメソッドつくらなきゃならなくなる。
### Concern

完全に前提Modと化す。

**Comment by shift02** [comment]
バニラクラスに実装する場合は、
バニラクラスを継承している他のModのクラスについて考える必要がある。

個人的にはinterfaceの情報を取得する専用のクラスを作成して、
そこでバニラのアイテムやブロックは例外的に処理をすればいいと思う。

**Comment by CrafterKina** [comment]
こちらで判定用メソッドを持つということか。
方針に反しないので、インターフェースでカバーできない範囲に限り、メソッドを作るという方向で行きたいと思う。
