### ISSUE TITLE
Interface method conflict(APIのメソッドがバニラとかぶる問題)

### ISSUE THREAD

**Issue by CrafterKina** [MinecraftModderJapan/MinecraftModCooperationAPI#11]
### Summary(概要)

こちらで用意したメソッドがバニラと被っているとMCPの難読化で危険な状態になる。
https://gist.github.com/CrafterKina/40424efcada94be7259a
### Content(内容)

ASMを使うことで回避することができる可能性がある。
Optionalで消される環境であればASMの処理は必要ないので問題ない。
### Reason(理由)
- エンチャントやポーションなど、Mod側で独自のシステムとして確立される可能性の高いものはバニラと名前がかぶらざるをえないメソッドが多い。
- Modのビルド環境で危険であるか危険でないかが変わってしまう。(ネームテーブルが異なる可能性)

**Comment by Verclene** [comment]
失礼します．
ASMによる書き換えを使ってまで同名メソッドをAPIで用意するというのはそれはそれで危険度は上がると思いますし，実装によっては他MODとの互換性の喪失を招きかねないのでは？
よほどのことがない限り，接頭辞か何かを使ってでもメソッド名に被りがないようにすれば安全ですし，APIを利用しての実装上でもそれほど大きな問題にはならないと考えます．

**Comment by shift02** [comment]
メソッドをバニラと被らせなければ問題ないと思います。

> エンチャントやポーションなど、Mod側で独自のシステムとして確立される可能性の高いものはバニラと名前がかぶらざるをえないメソッドが多い。

は、バニラ外のシステムまで考慮する必要はないと思います。

**Comment by CrafterKina** [comment]
ふむ。そうですか。
ではメソッド名は被らないようにし、万が一後のMCPのネームテーブルの変更などによって被ってしまった場合API側のメソッド名(や引数)を変えるという方向で行きますね。
