### ISSUE TITLE
Where We Distribute？(どこで配布するか)

### ISSUE THREAD

**Issue by CrafterKina** [MinecraftModderJapan/MinecraftModCooperationAPI#12]
このAPIをどこで配布するかについて、意見を伺いたいと思います。
Twitterでも少し話題に上がりましたが、記録として残す意味でもご協力願います。

現状、私が考えている配布場所の候補は
- マインクラフト非公式日本ユーザーフォーラム
  - 日本のModderが多い。
  - 現在不安定。
- GitHub
  - コミットとリリースとの関連付けができる。
  - 開発者向けである。
- Curse
  - 海外プレイヤーが多い。

の3つです。

**Comment by faroreJP** [comment]
配布は非公式とCurseのみとし、GitHubは議論と開発の場としてそれぞれのトピック内に誘導リンクを置くのはどうでしょう。

**Comment by shift02** [comment]
非公式で公開するのは賛成です。
Curseは非公式での反応を見てからでもいいかも

**Comment by CrafterKina** [comment]
なるほど。ではGithubはタグ貼るだけにして、とりあえず非公式フォーラムで公開してみますね。
