### ISSUE TITLE
The interface to the Capability System use(interfaceをCapability System利用にする)

### ISSUE THREAD

**Issue by shift02** [MinecraftModderJapan/MinecraftModCooperationAPI#16]
### Summary(概要)

IFoodやIBookをCapability Systemを使用したシステムに変える。
(1.9以降)

### Content(内容)

interfaceを直に実装するのではなくてCapability System経由で実装するようにする。
### Reason(理由)
- Capability SystemをForgeが勧めているから
- interfaceを実装をしなくてよくなりメソッド名被りなどを解決できる

**Comment by CrafterKina** [comment]
いいと思います。
もし具体的に、どういった構成にするのかなどが頭にあるのでしたらこの件はシフト氏にお任せしたいと思うのですが、どうでしょうか。

**Comment by shift02** [comment]
う～ん。　とりあえずIBookをCapability Systemを利用したシステムに変えてみて、反応を見てから本格的に取り組みたいと考えています

**Comment by CrafterKina** [comment]
なるほど。了解です。
ではこのIssueは開けたままにしておきますね。
