### ISSUE TITLE
To publish maven(mavenを公開する)

### ISSUE THREAD

**Issue by shift02** [MinecraftModderJapan/MinecraftModCooperationAPI#17]
### Summary(概要)

より簡単に利用できるようにmavenを用意する

### Content(内容)

mavenを利用した管理をできるようにする
### Reason(理由)
- gradleなどに2,3行追加すれば利用できるのはかなりの利点
- より利用しやすいように

**Comment by CrafterKina** [comment]
GithubPagesを用いてMavenRepositoryをたててみました。
MavenCentralへの登録は見送りました。
Gradleでの取り込み方についてはReleasesにて書いておきました。
問題が発生した場合は、MinecraftModderJapan.github.ioのリポジトリにてIssue建て願います。
