### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by S--Minecraft** [MinecraftModderJapan/MinecraftModCooperationAPI#2]
### Summary

具体的に何なのかわからない
### Content
- すべてのMODで使うインターフェース群
- 前提MODとして働きMODを開発しやすくする
  これらのうちどれかなのか、もしくはそれ以外なのか

常体で失礼しました

**Comment by S--Minecraft** [comment]
前者であれば、エンドユーザーでの導入は不要だが、後者であれば必要となってくる

前者と後者を組み合わせて、あるMODを利用する場合は導入が必要ないが、あるMODを利用する場合は導入が必要というパターンもある(？)

**Comment by CrafterKina** [comment]
Interfaceを付加するだけならば、Optionalの活用によって前提Modとはならない。
判定に用いる側は前提Modとしなければならないが、それを回避する手段が思いつかない。
(すべてのModが前提Modとしない場合、全く機能しなくなる。)

**Comment by CrafterKina** [comment]
何かというのを端的に表せば、インターフェース等を統合することによってそれぞれのModで抜けがあったりするのを防ぎ、結果的に連携を取りやすくするもの。
Utilityのように動いて開発をしやすくすることは目的ではない。

**Comment by S--Minecraft** [comment]
HTMLなどの規格のようなものではない？
ex. このような名前のメソッドはこのような動きをする というルール

**Comment by CrafterKina** [comment]
それは[こっち](https://github.com/MinecraftModderJapan/JapaneseMinecraftModificationStandards)でやること。
何も書いてないのでわかりづらいと思うが、鉱石辞書のプレフィックスなどにもそっちで言及する予定。

**Comment by S--Minecraft** [comment]
なるほど
