### ISSUE TITLE
The goal of this project

### ISSUE THREAD

**Issue by faroreJP** [MinecraftModderJapan/MinecraftModCooperationAPI#4]
### Summary

MinecraftModCooperationAPIの目指すものについて、より具体的に明文化したい。

### Content

MinecraftModCooperationAPIの掲げる最終的な目標および、どのようにしてその目標を達成するかのアプローチ（こちらはなくても可？）を具体的な文章にまとめ、READMEなどに記載する。
### Reason
- 現状でもREADMEには目標があるにはあるが、ふわふわしていて具体的に何なのかが分かりにくい。
- 複数人で進める（のかはまだ分からないけど・・・）以上、より有益な議論が行えるようにせめて目標は全メンバーで共通の知識にするべきでは？
- Twitterなどで外部からも意見を募るのであれば、やはり何を作ろうとしているのかが一見して分かったほうがよい

**Comment by faroreJP** [comment]
とりあえず現状ですが、README.mdにあるのは

> This API will be used to make your mods to work with other mods easily.

ですね。

現在は各種の判定用のInterfaceを追加する方針で実装を進めているようなので、
- 共通のインターフェースを用いてBlockやItemが何なのか（例えば、鉱石だったり食べ物だったり）を示すようにすることでmod間の連携を容易にする

みたいなのはどうでしょうか

**Comment by CrafterKina** [comment]
おおまかには異論ありません。
ただ、インターフェースのみを追加するにとどまらず、例えばShiftさんの提案にあったEnumDyeColorの追加等もタスクにありますので、

> 共通のインターフェースを用いて

とはできないと思います。

**Comment by faroreJP** [comment]
わかりました。
この件もですが、できれば私だけでなく他人の意見も聞きたいですね。

**Comment by CrafterKina** [comment]
参考:#2

**Comment by faroreJP** [comment]
なるほど

**Comment by faroreJP** [comment]
- 本APIは食べ物や色といった各modで内容が共通しやすいInterfaceやEnumを定義し、modderに提供する事で、mod間の連携を容易にすることを目的とする

みたいな感じですかね

**Comment by CrafterKina** [comment]
そうですね。
ところでもし、この目的から外れていて尚且つ必要性が高い案件が来た場合プロジェクトの別立てをするという方向でよろしいでしょうか。

**Comment by faroreJP** [comment]
> ところでもし、この目的から外れていて尚且つ必要性が高い案件が来た場合プロジェクトの別立てをするという方向でよろしいでしょうか。

そうですね。キナ氏や他の方に異論がないようであれば、MinecraftModCooperationAPIの目的は

> 本APIは食べ物や色といった各modで内容が共通しやすいInterfaceやEnumを定義し、modderに提供する事で、mod間の連携を容易にすることを目的とする

のようなもので確定させて、目的自体を今後変更することは避けるべきだと思います。
ただ、小規模のプロジェクトが大量発生することを危惧するのであれば、今の時点で目的の幅をちょっと広げて多少のブレを許容するようにするのもいいかと思います。

（例えば、

> 各modで内容が共通しやすいInterfaceやEnum

を

> 各modで内容が共通しやすい要素

にしておくなど）

**Comment by CrafterKina** [comment]
目的を固定化すべきという意見には同意です。
ただ、その固定化する目的についてはもう少し多くの意見が必要に思います。
私自身の意見としては、Fさん氏の

> 本APIは食べ物や色といった各modで内容が共通しやすいInterfaceやEnumを定義し、modderに提供する事で、mod間の連携を容易にすることを目的とする

で問題ないかと思っています。
もし、

> 各modで内容が共通しやすい要素

まで含んでしまうと、Utility群までカバーする可能性が出てくるからです。
Utilityまで含むべきであるという意見があるなら別ですが。

**Comment by shift02** [comment]
Utility群は含むべきではないと思います。

もし必要なら別のプロジェクトにした方がいいかと。

**Comment by faroreJP** [comment]
> 本APIは食べ物や色といった各modで内容が共通しやすいInterfaceやEnumを定義し、modderに提供する事で、mod間の連携を容易にすることを目的とする

ではこれでいきますか？

**Comment by CrafterKina** [comment]
そうですね。このIssueを解決するPRを立てますので、そちらでクローズしますね。
