### ISSUE TITLE
Creating a Japanese translation (日本語訳の作成)

### ISSUE THREAD

**Issue by shift02** [MinecraftModderJapan/MinecraftModCooperationAPI#5]
### Summary (概要)

MinecraftModderJapanなのに英語しかないのは如何なものか。
より多くの人に意見を募るのであれば日本語で書いてある方が理解しやすく
協力者も増えると考える。

### Content (コンテンツ)

英語の下に日本語でも併記する、もしくはREADME_JPのような日本語バージョンの作成。
- README.mdやISSUE_TEMPLATE.mdなどのGitHub関係のファイル
  →併記する
- issuesやlabelなどのGitHubのシステム
  →併記する
- Javadoc　
  →要検討
### Reason (理由)
- 非公式日本ユーザーフォーラムからの参加者が現状いない
- 英語だけだとお互いの認識に食い違いが出る可能性がある

**Comment by faroreJP** [comment]
日本語メインにすると分かりやすく敷居も低くなるのでより気軽に参加できるようになるので良いと思います。
ただ、個人的には、敷居が低い＝変な人が現れやすい、という懸念もありますが・・・。
それでも日本のmodder中心で進めるプロジェクトですので、やはり日本語訳は併記すべきだと思います

**Comment by CrafterKina** [comment]
いいと思います。
しかしその場合日本語訳は同じ場所にいれるのか、別ファイルとして作成するのか(ReadmeならReadme_jpなど)考える必要やJavadocなどのコード内テキストの扱いについて考える必要があると思います。

**Comment by shift02** [comment]
フォイルを分けることができる場合は_jpを作成する
分けることが出来ない場合(README.md)は併記するのがベストだと思います。

**Comment by CrafterKina** [comment]
> 分けることが出来ない場合(README.md)は併記するのがベストだと思います。

そうすると、現状分けることができるファイルはないように思いますね。
Javadocも日本語と英語の併記という形でいいでしょうか。
また、今のところPRやIssueはタイトル英語の議論日本語ですが、Shiftさんがやっているように日本語を併記するべきでしょうか、それとも英語を廃するべきでしょうか。
また、Labelも現在英語ですが日本語化することも可能です。これは英語のままにした方がいいでしょうか。

**Comment by faroreJP** [comment]
そもそも英語で記述している理由は何でしょうか？
もともと日本のもだー間での共通APIみたいな感じでこのプロジェクトが始まり、日本のもだー達で進めていくのあれば、英語を使用する必要はないと思います。

**Comment by shift02** [comment]
> また、今のところPRやIssueはタイトル英語の議論日本語ですが、Shiftさんがやっているように日本語を併記するべきでしょうか、それとも英語を廃するべきでしょうか。
> また、Labelも現在英語ですが日本語化することも可能です。これは英語のままにした方がいいでしょうか。

海外の人が見る可能性もあるのでPRやIssueは英語を主で日本語を併記するでいいと思います。

Labelなども同じくsuggestion (提案)などのように
GitHubをよく使う人や初心者でも分かりやすくする必要があると思います。

**Comment by shift02** [comment]
> そもそも英語で記述している理由は何でしょうか？
> もともと日本のもだー間での共通APIみたいな感じでこのプロジェクトが始まり、日本のもだー達で進めていくのあれば、英語を使用する必要はないと思います。

確かに…

英語で書いてある理由は何でしょうか？

**Comment by CrafterKina** [comment]
日本語ではなく英語を何故先に優先して書いたのか、という質問として答えます。
なぜならそれは、日本語を英語に翻訳するよりも英語を日本語に翻訳したほうが楽であると考えたからです。
日本語への翻訳は(当初)低く、まずは一般的な言語としての英語で書くのが優先であると考えていたからというのもあります。
しかし、日本のModder主体のプロジェクトですので、今すぐにでも日本語を併記すべきという意見には同意します。

**Comment by faroreJP** [comment]
なるほど・・・。
もともとは海外の方も参加することを想定されていたということでしょうか？
githubで進めていることもありますし、英語に日本語を併記するスタイルでいきますか？

**Comment by CrafterKina** [comment]
参加するかどうかは別として、APIとしての特性上多くの人の目に触れる可能性はあるので、どのような流れでこうなったのか等海外の方が参照する可能性は少なからずありますので、その辺を考慮しただけのことです。

**Comment by faroreJP** [comment]
なるほど。
それなら今後このAPIが普及したときの事も考えて英語も使用するべきですね。

**Comment by CrafterKina** [comment]
では、Javadocの日本語化について再提起しますね。
私は英語のみでも良いと思います。しかしJavadocを書く身としては、誤って伝わってしまうのではないか等いろいろ考えなくてはならないことも多く、日本語を併記すべきという意見には同意できます。
問題は、Javadocだと英語と日本語間で意味に違いが出ていると悪い影響が出てくることだと思います。

**Comment by CrafterKina** [comment]
あともうひとつ、完全に忘れていたのですが、コミットメッセージも日本語併記すべきですかね？
個人的には煩雑なのでなくてもいいと思っているんですが。

**Comment by faroreJP** [comment]
日本語を併記するメリットとして、分かりやすいというのはありますが・・・
コミットメッセージがどのくらいの長さになるのかは私は知らないのですが、例えば"Add new class"みたいな単純な文章で収まるのであれば日本語を併記する必要はないと思います。

**Comment by shift02** [comment]
コミットメッセージはfaroreJPさんのように単純だったら必要なし
でいいと思います

**Comment by CrafterKina** [comment]
なるほど了解です。二行以上になるなど長文になるようでしたら日本語を併記したいと思います。
そうならないように、コミットの粒度も下げますが。

Javadocはどうしましょうか。

**Comment by faroreJP** [comment]
このAPIは非公式フォーラムを中心に活動しているmodder達を対象とするものでしょうか？
でしたら、github以上に多くの方が参照するであろうjavadocは日本語を優先しつつ英語も併記するというのはいかがでしょうか。
（もちろん、コードを書く人にとっては負担が増えますが・・・）

**Comment by CrafterKina** [comment]
では、このIssueを解決するPRを立てるので、そちらでこのIssueをクローズしますね。
