### ISSUE TITLE
Proposed method (提案方法)

### ISSUE THREAD

**Issue by shift02** [MinecraftModderJapan/MinecraftModCooperationAPI#6]
### Summary (概要)

新しいインターフェイスや列挙型を追加(提案)する方法が不明確。

### Content (コンテンツ)

提案のテンプレートや手引きを作成する。
### Reason (理由)

新しいインターフェイスが欲しい時にどのようにすれば
MinecraftModCooperationAPIに追加する、もしくは議論して貰えるのかが分からない

**Comment by CrafterKina** [comment]
現在は、基本的なインターフェースをだいたい揃えるということをv1.0の目標に据えていますので、インターフェースのことであれば #3 にコメントがあれば議論できるかと思います。
Enumや #3 マージ後のInterface等については、IssueやPRを立ててもらえればそこで議論できると思います。
#3 クローズ前であっても、議論の重要度が高いと思われるInterfaceについては、IssueやPRがあればそこで議論できます。

と、いうことなんですが、これらのこともCONTRIBUTING.mdに記載する必要性がありますか？
個人的には、PRの説明のみ載っている現在のCONTRIBUTING.mdのままでも十分だと考えているのですが。

**Comment by shift02** [comment]
#3 を見なければ、議論をどこですればいいのか分からないという状態はやめたほうがいいと思います。
(「提案はここでします」とかをトップに記載するとか)

また

> Interface等については、IssueやPRを立ててもらえればそこで議論できると思います。

というルール？は、キナさんの頭のなかにあるだけでMinecraftModCooperationAPI内に記載はなく
初めて見た人が理解するのは難しい可能性があります。

**Comment by CrafterKina** [comment]
確かにGithubのシステムをあまり知らない方が、提案をしたい場合にIssueやPRを立てるということが思い当たらない可能性がありますね。
Readmeに提案等はIssueやPRでというふうに書いておいて、CONTRIBUTING.mdで詳細を書くという方向でいいでしょうか。
#3 の扱いは、新たなInterfaceやEnumの提案であればIssueやPRを別立てしていただいてまずいことはないので、特に記載しないという形で行きたいと思っていますがどうでしょうか。

**Comment by faroreJP** [comment]
とくに異論はありません

**Comment by S--Minecraft** [comment]
WIPPRをつくって実装しながらreviewをしてもらうか
またはIssueを建てて実装したのをreviewしてもらうか
の二通り程の方法があると思うのですが、
どちらで行くのでしょう？

**Comment by CrafterKina** [comment]
とりあえずこのIssueの”議論”は決着はついたとみなし、PR #8 で解決を行っていますので、議論はそっちへという方向になると思います。

**Comment by CrafterKina** [comment]
ああ、すいません。そういうことですか。
私としてはどちらもいいと思いますが、PRを提案者が立てる場合にはWIP-PRとしてたてて
そうではない場合はIssueを立てて担当者がPRを作成することになると思います。
盛り込むかどうかの議論はPR #8 でお願いします。
